class ConfigMenu

  class OptionTemp
    FONTFAMILY = [
      'sans-serif',
      'arial',
      'arial black',
      'arial narrow',
      'arial unicode ms',
      'Century Gothic',
      'Franklin Gothic Medium',
      'Gulim',
      'Dotum',
      'Haettenschweiler',
      'Impact',
      'Ludica Sans Unicode',
      'Microsoft Sans Serif',
      'MS Sans Serif',
      'MV Boil',
      'New Gulim',
      'Tahoma',
      'Trebuchet',
      'Verdana',
      'serif',
      'Batang',
      'Book Antiqua',
      'Bookman Old Style',
      'Century',
      'Estrangelo Edessa',
      'Garamond',
      'Gautami',
      'Georgia',
      'Gungsuh',
      'Latha',
      'Mangal',
      'MS Serif',
      'PMingLiU',
      'Palatino Linotype',
      'Raavi',
      'Roman',
      'Shruti',
      'Sylfaen',
      'Times New Roman',
      'Tunga',
      'monospace',
      'BatangChe',
      'Courier',
      'Courier New',
      'DotumChe',
      'GulimChe',
      'GungsuhChe',
      'HG行書体',
      'Lucida Console',
      'MingLiU',
      'ＭＳ ゴシック',
      'ＭＳ 明朝',
      'OCRB',
      'SimHei',
      'SimSun',
      'Small Fonts',
      'Terminal',
      'fantasy',
      'alba',
      'alba matter',
      'alba super',
      'baby kruffy',
      'Chick',
      'Croobie',
      'Fat',
      'Freshbot',
      'Frosty',
      'Gloo Gun',
      'Jokewood',
      'Modern',
      'Monotype Corsiva',
      'Poornut',
      'Pussycat Snickers',
      'Weltron Urban',
      'cursive',
      'Comic Sans MS',
      'HGP行書体',
      'HG正楷書体-PRO',
      'Jenkins v2.0',
      'Script',
      ['ヒラギノ角ゴ Pro W3', 'Hiragino Kaku Gothic Pro'],
      ['ヒラギノ角ゴ ProN W3', 'Hiragino Kaku Gothic ProN'],
      ['ヒラギノ角ゴ Pro W6', 'HiraKakuPro-W6'],
      ['ヒラギノ角ゴ ProN W6', 'HiraKakuProN-W6'],
      ['ヒラギノ角ゴ Std W8', 'Hiragino Kaku Gothic Std'],
      ['ヒラギノ角ゴ StdN W8', 'Hiragino Kaku Gothic StdN'],
      ['ヒラギノ丸ゴ Pro W4', 'Hiragino Maru Gothic Pro'],
      ['ヒラギノ丸ゴ ProN W4', 'Hiragino Maru Gothic ProN'],
      ['ヒラギノ明朝 Pro W3', 'Hiragino Mincho Pro'],
      ['ヒラギノ明朝 ProN W3', 'Hiragino Mincho ProN'],
      ['ヒラギノ明朝 Pro W6', 'HiraMinPro-W6'],
      ['ヒラギノ明朝 ProN W6', 'HiraMinProN-W6'],
      'Osaka',
      ['Osaka－等幅', 'Osaka-Mono'],
      'MS UI Gothic',
      ['ＭＳ Ｐゴシック','MS PGothic'],
      ['ＭＳ ゴシック','MS Gothic'],
      ['ＭＳ Ｐ明朝', 'MS PMincho'],
      ['ＭＳ 明朝', 'MS Mincho'],
      ['メイリオ', 'Meiryo'],
      'Meiryo UI'
    ]
  end
end